language: python
python:
  - 2.6
  - 2.7
sudo: false
cache:
  directories:
    - eggs
install:
  - pip install -r requirements_$TRAVIS_PYTHON_VERSION.txt
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q
script:
  - bin/code-analysis
  - bin/test
notifications:
  hipchat:
    secure: "vlk88+l3RvO982RKf0QonXnUvTUnrX8u/ZgoNbXm2iAUqcxy65B+e5u0a5wwcHKgH4bkkqENg+vbU38wB2+Y26ELNUyx/25YbdlTwMnnrHN9Vn9RRkCrwS+xHflaXApv131SYPzyHwja07hdU5pkGyCXf8GoDgg9r2BjhwpaB+A="
