language: python
python:
  - 2.6
  - 2.7
install:
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
branches:
  only:
    - master
script: bin/code-analysis && bin/py.test src/mls/apiclient/
notifications:
  irc: irc.freenode.org#propertyshelf
